import Head from 'next/head'
import Banner from '../components/banner/banner'
import SectionCards from '../components/card/section-cards'
import NavBar from '../components/nav/navbar'
import { getVidoes } from '../lib/videos'
import styles from '../styles/Home.module.css'

export default function Home() {
  const disneyVideos =  getVidoes();
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="halukdogan" />
      <Banner title='Clifford the red dog' subTitle='a very cute dog' imgUrl='/static/clifford.webp' />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Disney" videos={disneyVideos} size="medium" />
      </div>
    </div>
  )
}
